GET /test/api/categories HTTP/1.1
Host:localhost:9797
Accept: application/xml

###

GET /test/api/categories/2 HTTP/1.1
Host:localhost:9797
Accept: application/xml

###

GET /test/api/products/* HTTP/1.1
Host:localhost:9797
Accept: application/xml


###
GET /test/api/products/1/categories HTTP/1.1
Host:localhost:9797
# Accept: application/xml

###
GET /test/api/products?id=1&name=DARK HTTP/1.1
Host:localhost:9797
# Accept: application/xml

###
GET /test/api/categories/1/products HTTP/1.1
Host:localhost:9797
Accept: application/xml


###
GET /test/api/orders HTTP/1.1
Host:localhost:9797

###
GET /test/api/orders/ HTTP/1.1
Host:localhost:9797

###
GET /test/api/users HTTP/1.1
Host:localhost:9797
# Accept: application/xml

###
GET /test/api/users/3 HTTP/1.1
Host:localhost:9797
Accept: application/xml

###
Post /test/api/users HTTP/1.1
Host:localhost:9797
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<userDto>
  <email>hend12@gmail.com</email>
  <id>5</id>
  <password>1536</password>
  <phoneNumber>146556</phoneNumber>
  <userName>hendood</userName>
  <userType>ADMIN</userType>
  <wallet>700.0</wallet>
</userDto>
###

POST  /test/api/categories HTTP/1.1
Host:localhost:9797
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<categoryDto>
  <description>Woww</description>
  <id>4</id>
  <products>
    <id>1</id>
    <name>Dark</name>
    <description>Floorish</description>
    <quantity>0</quantity>
  </products>
  <value>soap</value>
</categoryDto>




